import { Token, NetworkId } from '@/types/blockchain';

// Popular tokens to show by default (even with 0 balance)
// These are well-known tokens on each network

export const DEFAULT_TOKENS: Record<NetworkId, Token[]> = {
  ethereum: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Ethereum',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    },
    {
      contractAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0x6B175474E89094C44Da98b954EescddeB131e232',
      symbol: 'DAI',
      name: 'Dai Stablecoin',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/9956/small/Badge_Dai.png',
    },
    {
      contractAddress: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
      symbol: 'WBTC',
      name: 'Wrapped Bitcoin',
      decimals: 8,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png',
    },
  ],
  polygon: [
    {
      contractAddress: null,
      symbol: 'MATIC',
      name: 'Polygon',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png',
    },
    {
      contractAddress: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    },
    {
      contractAddress: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619',
      symbol: 'WETH',
      name: 'Wrapped Ether',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
  ],
  arbitrum: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Ethereum',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    },
    {
      contractAddress: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0x912CE59144191C1204E64559FE8253a0e49E6548',
      symbol: 'ARB',
      name: 'Arbitrum',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg',
    },
  ],
  optimism: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Ethereum',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    },
    {
      contractAddress: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0x4200000000000000000000000000000000000042',
      symbol: 'OP',
      name: 'Optimism',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png',
    },
  ],
  base: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Ethereum',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb',
      symbol: 'DAI',
      name: 'Dai Stablecoin',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/9956/small/Badge_Dai.png',
    },
  ],
};

// Testnet tokens - native + common test ERC20 tokens from faucets
export const TESTNET_TOKENS: Record<NetworkId, Token[]> = {
  ethereum: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Sepolia ETH',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
      symbol: 'USDC',
      name: 'USD Coin (Sepolia)',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0x7169D38820dfd117C3FA1f22a697dBA58d90BA06',
      symbol: 'USDT',
      name: 'Tether USD (Sepolia)',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    },
    {
      contractAddress: '0x68194a729C2450ad26072b3D33ADaCbcef39D574',
      symbol: 'DAI',
      name: 'Dai Stablecoin (Sepolia)',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/9956/small/Badge_Dai.png',
    },
    {
      contractAddress: '0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14',
      symbol: 'WETH',
      name: 'Wrapped Ether (Sepolia)',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0x779877A7B0D9E8603169DdbD7836e478b4624789',
      symbol: 'LINK',
      name: 'Chainlink (Sepolia)',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
    },
  ],
  polygon: [
    {
      contractAddress: null,
      symbol: 'MATIC',
      name: 'Amoy MATIC',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png',
    },
    {
      contractAddress: '0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582',
      symbol: 'USDC',
      name: 'USD Coin (Amoy)',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0x360ad4f9a9A8EFe9A8DCB5f461c4Cc1047E1Dcf9',
      symbol: 'USDT',
      name: 'Tether USD (Amoy)',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    },
    {
      contractAddress: '0x0Fd9e8d3aF1aaee056EB9e802c3A762a667b1904',
      symbol: 'LINK',
      name: 'Chainlink (Amoy)',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
    },
  ],
  arbitrum: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Arbitrum Sepolia ETH',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d',
      symbol: 'USDC',
      name: 'USD Coin (Arb Sepolia)',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0xb1D4538B4571d411F07960EF2838Ce337FE1E80E',
      symbol: 'LINK',
      name: 'Chainlink (Arb Sepolia)',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
    },
  ],
  optimism: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Optimism Sepolia ETH',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0x5fd84259d66Cd46123540766Be93DFE6D43130D7',
      symbol: 'USDC',
      name: 'USD Coin (OP Sepolia)',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0xE4aB69C077896252FAFBD49EFD26B5D171A32410',
      symbol: 'LINK',
      name: 'Chainlink (OP Sepolia)',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
    },
  ],
  base: [
    {
      contractAddress: null,
      symbol: 'ETH',
      name: 'Base Sepolia ETH',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: true,
      logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
      contractAddress: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
      symbol: 'USDC',
      name: 'USD Coin (Base Sepolia)',
      decimals: 6,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    },
    {
      contractAddress: '0xE4aB69C077896252FAFBD49EFD26B5D171A32410',
      symbol: 'LINK',
      name: 'Chainlink (Base Sepolia)',
      decimals: 18,
      balance: '0',
      balanceFormatted: '0',
      balanceUsd: null,
      isNative: false,
      logoUrl: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
    },
  ],
};

export function getDefaultTokens(networkId: NetworkId, isTestnet: boolean): Token[] {
  return isTestnet ? TESTNET_TOKENS[networkId] : DEFAULT_TOKENS[networkId];
}
